version: "3.8"

services:
    app:
        build:
            context: .
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        ports:
            - "8000:80"
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: laravel-db
        environment:
            POSTGRES_DB: mathites_db
            POSTGRES_USER: mathites_db_user
            POSTGRES_PASSWORD: XWqsu8JhFgslNdRooXDcAhSWQGq3BUWb
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
