/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "\u0391\u03c1\u03c7\u03b9\u03ba\u03ae": [],
    "video": [],
    "\u03a0\u03bf\u03b9\u03bf\u03b9\u0395\u03af\u03bc\u03b1\u03c3\u03c4\u03b5": [],
    "blog": [],
    "\u0394\u03b9\u03b1\u03b3\u03c9\u03bd\u03b9\u03c3\u03bc\u03cc\u03c2": [],
    "\u0395\u03c0\u03b9\u03ba\u03bf\u03b9\u03bd\u03c9\u03bd\u03af\u03b1": [],
    "\u0394\u03b7\u03bc\u03b9\u03bf\u03c5\u03c1\u03b3\u03af\u03b5\u03c2": [],
    "craft": [
        {
            "name": "craft",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "admin.create": [],
    "admin.store": [],
    "craft.edit": [
        {
            "name": "craft",
            "required": true,
            "binding": "id"
        }
    ],
    "craft.destroy": [
        {
            "name": "craft",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
